STORMPATH_CLIENT_APIKEY_ID=5HT6YTKYXK6A9QEE81WJHOKW8
STORMPATH_CLIENT_APIKEY_SECRET=EICS5HDuyN6cNGklV85QhyuDNNqqhqxJJy5aTCqlfJc
STORMPATH_APPLICATION_HREF=https://api.stormpath.com/v1/applications/1EYz5Tf6iRsEjqryag42U5
